openapi: 3.0.1
info:
  title: Hello Completable API
  description: Public API for Testing openApi/Swagger with Micronaut and Completables
  version: "1.0"
servers:
- url: https://example.com
tags:
- name: /hello
paths:
  /hello/completable:
    get:
      tags:
      - /hello
      operationId: Completable
      parameters: []
      responses:
        default:
          content:
            application/json: {}
